//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTAuthTest {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JWTAuthTest.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NEST_RESULT_HTTP_400 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_400", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_401 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_401", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_403 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_403", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_ERROR {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_ERROR", resourceCulture);
            }
        }
        
        internal static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        internal static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        internal static string IncorrectSecurityCode {
            get {
                return ResourceManager.GetString("IncorrectSecurityCode", resourceCulture);
            }
        }
        
        internal static string InvalidPermit {
            get {
                return ResourceManager.GetString("InvalidPermit", resourceCulture);
            }
        }
        
        internal static string InvalidShare {
            get {
                return ResourceManager.GetString("InvalidShare", resourceCulture);
            }
        }
        
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
    }
}
